name: Docker build
on: push
jobs:
  docker:
    runs-on: gh-runner-own-59bc9dff6f-kbt4t
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: mahmoudaboghadeer93/action-kaniko@master
        with:
          image: mhmud/kaniko
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: mhmud/cache
